In [1]:
import pandas as pd
import numpy as np

In [2]:
cars = pd.read_csv('../dataset/true_car_listings.csv')
cars

,Price,Year,Mileage,City,State,Vin,Make,Model
0,8995,2014,35725,El Paso,TX,19VDE2E53EE000083,Acura,ILX6-Speed
1,10888,2013,19606,Long Island City,NY,19VDE1F52DE012636,Acura,ILX5-Speed
2,8995,2013,48851,El Paso,TX,19VDE2E52DE000025,Acura,ILX6-Speed
3,10999,2014,39922,Windsor,CO,19VDE1F71EE003817,Acura,ILX5-Speed
4,14799,2016,22142,Lindon,UT,19UDE2F32GA001284,Acura,ILXAutomatic
...,...,...,...,...,...,...,...,...
852117,63215,2017,9,Culver City,CA,YV1A22MK9H1013237,Volvo,S90T6
852118,72260,2017,3201,Englewood,NJ,YV4A22PL3H1186162,Volvo,XC90T6
852119,55999,2016,28941,Fort Collins,CO,YV4A22PL4G1000868,Volvo,XC90AWD
852120,60240,2017,3005,San Leandro,CA,YV4A22NLXH1006162,Volvo,V90
852121,76995,2017,2502,New York,NY,YV4BC0ZX1H1109845,Volvo,XC90T8

In [3]:
cars.sample(5)

,Price,Year,Mileage,City,State,Vin,Make,Model
525924,14000,2016,13809,Rock Hill,SC,KNADM5A36G6686237,Kia,Rio5-door
194180,4995,2007,96000,Newport News,VA,1C3LC56K17N562694,Chrysler,Sebring
816777,29997,2015,33388,D'Iberville,MS,JTEZU5JR8F5104040,Toyota,4Runner4x2
820203,41498,2015,24930,Saint Cloud,FL,5TFDW5F11FX444937,Toyota,Tundra
239577,10999,2015,43590,Peoria,AZ,3FA6P0H75FR244894,Ford,FusionSE

In [4]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852122 entries, 0 to 852121
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Price    852122 non-null  int64
 1   Year     852122 non-null  int64
 2   Mileage  852122 non-null  int64
 3   City     852122 non-null  object
 4   State    852122 non-null  object
 5   Vin      852122 non-null  object
 6   Make     852122 non-null  object
 7   Model    852122 non-null  object
dtypes: int64(3), object(5)
memory usage: 52.0+ MB

In [7]:
cars.drop(columns=["Vin","State","City"],inplace=True)

In [12]:
np.set_printoptions(threshold=np.inf)
cars["Model"].unique()

array(['ILX6-Speed', 'ILX5-Speed', 'ILXAutomatic', 'TSXAutomatic',
       'TSXSpecial', 'TSX5-Speed', 'TSX4dr', 'TSX', 'ILX4dr',
       'ILXAcuraWatch', 'ILXHybrid', 'TSXManual', 'TSXPremium',
       'ILXPremium', 'ILXTechnology', 'TL4dr', 'TL2WD', 'TLBase',
       'TLSpecial', 'TLAutomatic', 'TSXV6', 'TLwith', 'TLSH-AWD',
       'TLType-S', 'TLManual', 'RDXFWD', 'TLXFWD', 'RDX4WD', 'RDXAWD',
       'RSXAutomatic', 'RDXwith', 'RSXType-S',
       'RDX*1-OWNER*LTHR*ROOF*BACK-UP*TECH', 'RSXManual', 'SLX4WD',
       'RDXBase', 'RLAutomatic', 'CLAutomatic', 'TLXSH-AWD', 'CLType-S',
       'MDX4WD', 'ZDXAWD', 'RL4dr', 'MDXAWD', 'TL3.2', 'IntegraGS',
       'MDXACURA', 'MDXBase', 'IntegraLS', 'MDXFWD', 'ZDXBase',
       'CLManual', 'MDXwith', 'RLXwith', 'RLXBase', 'MDXSH-AWD',
       'RLXAutomatic', 'IntegraRS', 'MDXAdvance', 'RLXHybrid', 'MDX3.5L',
       'MDXSport', 'NSXManual', 'NSXCoupe', 'Romeo', 'General', 'Martin',
       'A44dr', 'A42dr', 'A42007.5', 'A42004', 'A42.0T', 'A45dr',
       'A42005', 'A42007', 'A42004.5', 'A42005.5', 'A3Sedan', 'A34dr',
       'A64dr', 'A52.0T', 'A52dr', 'A32.0T', 'A4AWD', 'A4Premium',
       'A4ultra', 'A62.0T', 'A3Cabriolet', 'S3Premium', 'A63.0T', 'S44dr',
       'A84dr', 'S42dr', 'Q5quattro', 'A4Season', 'A3', 'S42007',
       'Q7quattro', 'A8', 'Q52.0T', 'TTS2dr', 'S45dr', 'TT2dr',
       'allroad5dr', 'S42005.5', 'S4quattro', 'S42007.5', 'Q3FrontTrak',
       'Q53.0T', 'Q3quattro', 'allroad2.0T', 'S84dr', 'Q3Premium',
       'A63.0TDI', 'Q73.0T', 'Q52.0', 'TTSCoupe', 'S52dr', 'S3Prestige',
       'Q53.2L', 'A4Prestige', 'RS64dr', 'A6CERTIFIED', 'TT180hp',
       'S64dr', 'TTCoupe', 'S4Quattro', 'A5', 'A62016', 'SQ5quattro',
       'S3quattro', 'TT3.2L', 'RS44dr', 'TTRoadster', 'S5Coupe', 'RS42dr',
       'Q53.0TDI', 'Q53.0', 'Q5Premium', 'S5Cabriolet', 'A73.0T', 'TTSS',
       'TT', 'SQ5Premium', 'A83.0T', 'A74dr', 'Q73.0TDI', 'TTSRoadster',
       'S6quattro', 'A84.0T', 'S7quattro', 'S5', 'TTS2.0', 'A6Premium',
       'allroadPremium', 'Q72.0T', 'RS', 'A84.2L', 'S4Premium',
       'SQ5Prestige', 'S8quattro', 'A73.0TDI', 'S6Premium', 'Q73.0',
       'S6Prestige', 'allroadPrestige', 'A7Premium', 'A7Prestige',
       'A7Competition', 'R82dr', 'S7Premium', 'S7Prestige', 'S8Sedan',
       'S4Prestige', 'R84.2FSI', 'S8Plus', 'R85.2', 'S8', 'R85.2FSI',
       'R8Auto', 'R8', 'Continental', 'Arnage4dr', 'Continental2dr',
       'Azure2dr', 'Brooklands2dr', 'Flying', 'Mulsanne4dr',
       'MulsanneBase', 'MulsanneSedan', 'ContinentalGT', 'BentaygaW12',
       'MulsanneSpeed', '3', 'X1sDrive28i', '5', 'X1xDrive28i', '1',
       'i3Hatchback', 'X3AWD', 'X1xDrive35i', 'X3xDrive28i', 'X1xDrive',
       'X5AWD', '7', 'X3sDrive28i', 'X3xDrive35i', '2', 'Z4Roadster',
       'X5xDrive35i', 'X5', 'X1Sports', '6', 'Z42dr', 'X1AWD',
       'Z3Roadster', '4', 'X5xDrive50i', 'X3xDrive28d', 'X5xDrive35d',
       'X4xDrive28i', 'X6AWD', 'Z4Coupe', 'i394', 'X5sDrive35i', 'Z3Z3',
       'X535i', 'Z4sDrive28i', 'Z4sDrive35i', 'Z4Z4', 'X4xDrive35i', 'X6',
       'X6xDrive35i', 'Z3Coupe', 'X6xDrive50i', 'M34dr', 'M32dr', 'M62dr',
       'M54dr', 'Z4sDrive35is', 'M3M3', 'M3Convertible', 'X4xDriveM40i',
       '8', 'X6sDrive35i', 'M3Coupe', 'M5Sedan', 'M4Coupe', 'M2Coupe',
       'X5xDrive40e', 'X4M40i', 'M6Convertible', 'M6M6', 'M3Sedan',
       'M4Convertible', 'M6Coupe', 'Verano1SD', 'VeranoBase',
       'VeranoSport', 'VeranoConvenience', 'VeranoVerano', 'Verano4dr',
       'VeranoLeather', 'Rendezvous4dr', 'Verano1SV', 'RendezvousFWD',
       'Verano', 'VeranoPremium', 'VeranoTurbo', 'RendezvousCX',
       'RendezvousCXL', 'VeranoFWD', 'Terraza4dr', 'EncoreFWD',
       'EncoreConvenience', 'EncoreLeather', 'EncorePremium',
       'EncoreEncore', 'EncoreAWD', 'EncoreSport', 'LaCrosse4dr',
       'LaCrosseFWD', 'Lucerne4dr', 'LaCrosseAWD', 'Regal4dr',
       'Skylark4dr', 'Encore', 'RegalTurbo', 'RegalPremium', 'RegalSport',
       'RegalBase', 'RegalRegal', 'Regal4DR', 'LaCrosseLeather',
       'Rainier4dr', 'VeranoSedan', 'LeSabre4dr', 'RegalFWD',
       'LaCrosseCXL', 'Regal', 'Regal1FL', 'RegalGS', 'CascadaPremium',
       'RegalSedan', 'RainierRWD', 'EnclaveFWD', 'RegalBARGAIN',
       'RegalFleet', 'RainierAWD', 'EnclaveAWD', 'EnclaveConvenience',
       'Riviera2dr', 'Century4dr', 'EnclaveLeather', 'EnvisionFWD',
       'EnclaveBase', 'EnvisionAWD', 'EnvisionPremium', 'EnclavePremium',
       'CascadaConvertible', 'CascadaSport', 'Park', 'CenturyCustom',
       'LeSabreLimited', 'LaCrossePremium', 'Regal97.5', 'CenturyCUSTOM',
       'CTS4dr', 'ATS2.5L', 'ATS2.0L', 'CTS', 'ATS3.6L', 'STS4dr',
       'SRXRWD', 'ATS', 'DTS4dr', 'SRX4dr', 'SRXAWD', 'Seville4dr',
       'DeVille4dr', 'SRXFWD', 'SRXBase', 'Catera4dr', 'SRXLuxury',
       'DeVille', 'XLR2dr', 'SRXStandard', 'DeVilleBase',
       'SRXPerformance', 'SRXPremium', 'DeVilleSedan', "d'Elegance4dr",
       'Concours4dr', 'DeVille4d', 'SRXLeather', 'XT5Standard', 'SRX3.6',
       'STS-V4dr', 'XTSLuxury', 'XTSBase', 'Eldorado2dr', 'Escalade',
       'XTSFWD', 'STS-VSTS-V', 'Escalade4dr', 'CTS-VCTS-V', 'XTS3.6L',
       'ELRCoupe', 'XTSPremium', 'XTSPlatinum', 'XT5Luxury', 'XTSAWD',
       'EscaladeAWD', 'CTS-V4dr', 'XTSVsport', 'Escalade2WD', 'XTS',
       'XLR-VXLR-V', 'CT6', 'XT5Premium', 'EscaladeRWD', 'XT5Platinum',
       'ATS-V', 'CTS-V', 'XLR-V2dr', 'EscaladeLuxury', 'EscaladePremium',
       'EscaladePlatinum', 'EscaladeBase', 'XTSTurbo', 'XT5FWD',
       'Escalade4WD', 'CruzeSedan', 'EquinoxFWD', 'MalibuLS', 'MalibuLT',
       'Malibu1LT', 'Malibu4dr', 'CruzeL', 'CruzeLS', 'Malibu2LT',
       'Cruze1LT', 'MalibuFleet', 'Malibu', 'CruzeLT', 'Malibu4d',
       'Cruze4dr', 'Malibu2LZ', 'Cruze2LT', 'Aveo5dr', 'CruzeHatchback',
       'CruzeECO', 'MalibuECO', 'Aveo1LT', 'Malibu4DR', 'Tahoe2WD',
       'Malibu1LTZ', 'MalibuL', 'CruzeLTZ', 'Malibu1LZ', 'Aveo4dr',
       'Spark', 'Malibu3LT', 'MalibuBase', 'EquinoxAWD', 'CruzePremier',
       'TraxFWD', 'Malibu1FL', 'MalibuSEDAN', 'SonicSedan',
       'MalibuClassic', 'Cobalt4dr', 'MalibuSedan', 'SonicHatch',
       'Equinox4dr', 'CruzeDiesel', 'Malibu2LTZ', 'Cobalt2dr',
       'MalibuHybrid', 'Equinox2WD', 'TraxAWD', 'MalibuLTZ', 'Cruze',
       'SonicHatchback', 'Cruze4d', 'MalibuPremier',
       'MalibuFleet*1-Owner*Clean', 'ImpalaLimited', 'Cruze1FL',
       'ImpalaLT', 'Impala4dr', 'Captiva', 'Trax', 'SparkLS',
       'ImpalaPolice', 'Impala1LT', 'Silverado', 'ImpalaLS', 'City',
       'Impala1LTZ', 'EquinoxLT', 'Equinox4d', 'Spark1LT', 'Colorado2WD',
       'CamaroCoupe', 'ImpalaUnmarked', 'Equinox', 'Impala4d',
       'EquinoxLTZ', 'CobaltSS', 'ImpalaLTZ', 'Uplander', 'Impala4',
       'ImpalaSEDAN', 'Impala2LT', 'ImpalaSedan', 'Camaro2dr', 'Impala',
       'Impala1LS', 'Trax1LT', 'ImpalaLT2', 'EquinoxLS', 'Spark2LT',
       'TraverseFWD', 'ColoradoRegular', 'Camaro2LS', 'CamaroConvertible',
       'Cavalier4dr', 'VoltBase', 'VoltPlug-In', 'TraverseAWD',
       'Camaro1LS', 'Uplander4dr', 'CamaroLS', 'ImpalaImpala',
       'ColoradoExtended', 'Cavalier2dr', 'Chevy', 'Colorado4WD',
       'Volt5dr', 'TraverseLS', 'Impala2LTZ', 'TrailBlazer2WD',
       'TrailBlazer4WD', 'TrailBlazer4dr', 'Impala3LT', 'CruzeLs',
       'HHRFWD', 'Express', 'ImpalaPremier', 'C/K', 'Tracker4dr',
       'HHR4dr', 'Traverse1LT', 'Traverse2LT', 'ColoradoCrew',
       'Tracker2dr', 'HHR2WD', 'Tahoe4dr', 'Monte', 'S-102WD', 'CamaroLT',
       'VoltLT', 'TahoeLS', 'Tahoe', 'Suburban4dr', 'Blazer2dr',
       'Camaro1LT', 'TahoePolice', 'Blazer4dr', 'S-104WD', 'BlazerFleet',
       'Prizm4dr', 'VentureExt', 'TraverseLTZ', 'Astro', 'New',
       'Tahoe4WD', 'AveoLT', 'VentureReg', 'VoltPremier',
       'TahoeCommercial', 'Lumina4dr', 'TahoeHeated', 'TahoeSpecial',
       'Avalanche1500', 'Impala2', 'Suburban4WD', 'C', 'Bolt',
       'ImpalaFirst', 'Venture4dr', 'Camaro', 'Corvette2dr',
       'Suburban2WD', 'TahoeLT', 'SonicLT', 'SSSedan', 'AvalancheLT',
       'SuburbanLS', 'Suburban1500', 'Avalanche2WD', 'Avalanche4WD',
       'Tahoe2dr', 'Tahoe1500', 'Suburban2500', 'SuburbanLT',
       'Suburban3/4', 'SuburbanFleet', 'TahoeLTZ', 'Avalanche2500',
       'AvalancheLS', 'SSRRegular', 'Suburban', 'Spark4DR',
       'CorvetteConvertible', 'CorvetteCoupe', 'SuburbanLTZ',
       'AvalancheLTZ', 'TrailBlazerLS', 'CamaroSS', 'Camaro2SS',
       'Venture', 'P', 'Corvette', 'CorvetteStingray', 'TahoePremier',
       'Corvette427', 'CorvetteZ06', 'CorvetteZ51', 'CorvetteGrand',
       'CorvetteZR1', 'AspenAWD', 'AspenRWD', 'Aspen2WD', 'Pacifica4dr',
       'Aspen4WD', '200Sedan', '200Limited', '200LX', '200S', '2004dr',
       '2002dr', '200Convertible', '200Touring', '200', '200C',
       'PacificaLX', '3004dr', 'Crossfire2dr', 'Pacifica2004', '300300',
       'PacificaTouring', '300Limited', '300300S', 'PacificaTouring-L',
       '300300C', '300Uptown', 'Sebring4dr', '300Motown', 'Sebring2dr',
       'Sebring', '300Luxury', 'Town', 'Sebring2004', '300M4dr',
       'Sebring2004.5', '300C', '300John', 'PT', '300Anniversary',
       'Cirrus4dr', 'LHS4dr', 'Concorde4dr', 'PacificaLimited', '300SRT8',
       'Voyager4dr', 'SebringTouring', 'Prowler2dr', 'PacificaHybrid',
       'ChargerSE', 'AvengerSE', 'Caliber4dr', 'AvengerSXT', 'Avenger4dr',
       'CaliberSXT', 'Charger4dr', 'Charger', 'ChargerSXT', 'Caliber',
       'AvengerR/T', 'ChargerRT', 'DartSXT', 'Charger4d', 'ChargerPolice',
       'Magnum4dr', 'ChargerV6', 'Grand', 'DartSE', 'ChargerBase',
       'JourneySE', 'ChargerAWD', 'CaliberExpress', 'JourneyFWD',
       'DartAero', 'ChargerRoad/Track', 'Neon4dr', 'DartRallye',
       'ChargerR/T', 'DartGT', 'ChallengerSXT', 'JourneySXT',
       'JourneyAmerican', 'Stratus', 'DartLimited', 'Ram', 'JourneyAWD',
       'Challenger2dr', 'Avenger2dr', 'JourneyR/T', 'Caravan',
       'JourneyCrossroad', 'Dart', 'DartSXT/Rallye', 'JourneyCrew',
       'Nitro2WD', 'ChallengerRallye', 'JourneyGT', 'JourneyLimited',
       'Nitro4WD', 'ChargerSRT8', 'NitroSE', 'ChargerDaytona', 'NitroSXT',
       'Dakota2WD', 'Challenger', 'ChallengerR/T', 'Dakota4WD',
       'Durango4dr', 'Durango2WD', 'NitroSLT/RT', 'Durango4WD', 'Journey',
       'Sprinter3500', 'CaravanSE', 'Stratus2004', 'Stratus2dr',
       'NitroR/T', 'DurangoSXT', 'ChallengerShaker', 'Caravan4dr',
       'NeonSE', 'Stratus4dr', 'CaravanSport', 'CaravanSXT',
       'ChallengerGT', 'NitroSPORT', 'DurangoAWD', 'ChargerPursuit',
       'CaliberHB', 'ChallengerSRT8', 'ChargerFleet', 'Sprinter',
       'Intrepid4dr', 'DurangoCrew', 'DakotaBighorn/Lonestar',
       'Sprinter2500', 'CaravanEX', 'ChargerSRT', 'DurangoLimited',
       'Caravan4', 'DurangoGT', 'DurangoSpecial', 'DurangoCitadel',
       'ChallengerT/A', 'CaravanES', 'StratusSE', 'ChallengerScat',
       'DurangoPolice', 'Caravan3', 'DurangoCREW', 'ChallengerSRT',
       'DurangoR/T', 'Challenger392', 'Neonsx', 'Nitro', 'Stratus2004.5',
       'ChargerSCATPK', 'Viper2dr', 'SRT', 'ViperGTS', 'ViperGTC',
       'ViperSRT', 'ViperACR', '3602dr', '430Coupe', 'California2dr',
       '612', '4302dr', '430Convertible', 'CaliforniaConvertible', '575M',
       '430Spider', '599', 'FF2dr', '458', 'FFHatchback', '360Challenge',
       'California', '488', 'F12berlinettaCoupe', 'F12berlinetta2dr',
       'GTC4LussoCoupe', '500eBATTERY', '500e', '500XFWD', '500',
       '500XAWD', '500LEasy', '500XPop', '500Pop', '500XLounge',
       '500Easy', '500Sport', '500XTrekking', '500Ribelle', '500LPop',
       '500LTrekking', '500Lounge', '500Turbo', '500LLounge', '500Abarth',
       '500cPop', '500Gucci', '5001957', '124', '500LUrbana',
       '500cLounge', '500cAbarth', '500cGQ', 'Karma4dr', 'KarmaEcoSport',
       'Taurus', 'Focus', 'FusionS', 'FusionSE', 'FocusS',
       'FocusHatchback', 'FocusSedan', 'Fusion4dr', 'FiestaHatchback',
       'FusionHybrid', 'FiestaSE', 'FiestaSedan', 'FocusSE',
       'FusionTitanium', 'FiestaS', 'C-Max', 'Focus4dr', 'FocusSEL',
       'Focus5dr', 'Fiesta4dr', 'EscapeFWD', 'Five', 'Edge4dr',
       'Fiesta5dr', 'Fusion', 'EscapeS', 'Focus2dr', 'Focus3dr',
       'FocusTitanium', 'EscapeTitanium', 'FiestaTitanium', 'EscapeSE',
       'FusionPlatinum', 'Escape4dr', 'Escape4WD', 'FocusST', 'ZX22dr',
       'MustangConvertible', 'Escape2WD', 'FusionSEL', 'F-1502WD',
       'MustangCoupe', 'EscapeSEL', 'Mustang2dr', 'F-150XL', 'F-1504WD',
       'EdgeSE', 'MustangV6', 'MustangFastback', 'F-150', 'ExplorerRWD',
       'FiestaST', 'TaurusSE', 'Explorer4dr', 'EscapeXLS', 'Explorer4WD',
       'EdgeSEL', 'Transit', 'ExplorerBase', 'Super', 'MustangEcoBoost',
       'F-150Regular', 'EdgeFWD', 'EdgeLimited', 'TaurusSEL',
       'EscapeSPORT', 'Mustang', 'F-150XLT', 'Freestyle4dr',
       'FusionSport', 'EdgeAWD', 'ExplorerFWD', 'Taurus4dr',
       'Expedition4WD', 'F-150SuperCab', 'Explorer2dr', 'TaurusLimited',
       'Explorer2WD', 'ExplorerAWD', 'Econoline', 'EscapeBase',
       'F-2502WD', 'ExplorerXLT', 'Freestar', 'TaurusPolice',
       'ExplorerPolice', 'Ranger2WD', 'ExplorerLimited', 'F-150SuperCrew',
       'TaurusSHO', 'Expedition5.4L', 'Escort2dr', 'EdgeSport',
       'EdgeTitanium', 'Explorer', 'Expedition119"', 'Expedition4dr',
       'Crown', 'Windstar', 'MustangGT', 'Expedition2WD', 'F-3502WD',
       'Club', 'Contour4dr', 'RangerXL', 'EdgeLTD', 'Expedition4.6L',
       'ExplorerSport', 'F-2504WD', 'F-250', 'Flex4dr', 'Expedition',
       'Ranger4WD', 'FlexSE', 'F-150Platinum', 'Escort4dr',
       'ExpeditionXLT', 'E-Series', 'ExpeditionLimited',
       'ExpeditionEddie', 'FlexSEL', 'F-150Lariat', 'EscortSE',
       'FlexLimited', 'F-350', 'F-150Limited', 'F-150AWD', 'Ranger',
       'Thunderbird2dr', 'FocusRS', 'EscortFleet', 'ExpeditionXL',
       'Excursion137"', 'ExpeditionKing', 'F-150FX4', "F-150'07",
       'F-1502010', 'MustangShelby', 'F-150King', 'F-150SVT',
       'Excursion2005', 'RangerEdge', 'ExpeditionEL',
       'ExpeditionPlatinum', 'F-150Raptor', 'MustangCobra', 'GT2dr',
       'G803.8L', 'G805.0L', 'G903.3T', 'G905.0L', 'TerrainAWD',
       'TerrainFWD', 'Sierra', 'AcadiaFWD', 'TerrainSLE-2', 'TerrainSLT',
       'AcadiaAWD', 'CanyonExtended', 'CanyonRegular', 'Yukon',
       'Canyon2WD', 'Savana', 'Safari', 'Envoy2WD', 'Envoy4dr',
       'Envoy4WD', 'Classic', 'Envoy', 'Canyon4WD', 'CanyonCrew',
       'Yukon4dr', 'Denali4dr', 'Jimmy4dr', 'CanyonSLE', 'Yukon2WD',
       'AcadiaSLE', 'Sonoma4WD', 'Sonoma2WD', 'Yukon4WD', 'Acadia',
       'Jimmy2dr', 'YukonAWD', 'YukonSLE', 'TerrainSLT-1', 'YukonSLT1',
       'Yukon1500', 'YukonXL', 'YukonCOMMERCIAL', 'YukonDenali', 'Civic',
       'Accord', 'CR-Z3dr', 'CR-ZEX', 'CR-ZCVT', 'InsightLX',
       'CR-ZManual', 'InsightBase', 'CivicSi', 'FitAutomatic',
       'CR-ZAutomatic', 'FitLX', 'FitEX-L', 'Fit5dr', 'FitEX', 'FitSport',
       'Insight5dr', 'InsightEX', 'FitManual', 'CR-ZLX', 'InsightCVT',
       'CR-VEX-L', 'CivicEX', 'CivicGX', 'CivicContinuously', 'CivicLX',
       'CR-ZEX-L', 'Fit', 'CivicVP', 'CivicManual', 'CR-VLX', 'CR-VEX',
       'CR-V2WD', 'HR-V2WD', 'HR-VLX', 'CR-V4WD', 'CR-VSE',
       'InsightContinuously', 'HR-VAWD', 'HR-VEX', 'HR-VEX-L',
       'Odyssey5dr', 'CivicDX', 'Pilot4WD', 'OdysseyLX', 'CivicCX',
       'OdysseyEX', 'Pilot2WD', 'CR-V', 'CrosstourEX-L', 'Prelude2dr',
       'CrosstourEX', 'OdysseyEX-L', 'CR-VTouring', 'Odyssey4dr',
       'OdysseyEX-RES', 'Element4WD', 'PilotEX-L', 'PilotLX',
       'Ridgeline4WD', 'PilotEX', 'OdysseySE', 'OdysseyTouring',
       'RidgelineSport', 'RidgelineRTS', 'RidgelineRT', 'CR-VAutomatic',
       'Passport4WD', 'PreludeAutomatic', 'RidgelineSE', 'RidgelineRTL',
       'Element2WD', 'PilotSE', 'OdysseyMINI', 'PilotTouring',
       'Passport2WD', 'RidgelineRTL-T', 'CivicHX', 'CR-VONE', 'S20002dr',
       'S2000Manual', 'Odyssey2005', 'RidgelineBlack', 'RidgelineRTL-E',
       'InsightManual', 'PilotElite', 'OdysseyElite', 'Pilot', 'H34dr',
       'H34WD', 'H3Alpha', 'H3', 'H3H3T', 'H24WD', 'H24dr',
       'H14-Passenger', 'Sonata', 'ElantraSE', 'Sonata2.4L',
       'ElantraLimited', 'SonataSE', 'SonataGLS', 'Elantra4dr',
       'Sonata4dr', 'ElantraValue', 'ElantraGLS', 'Elantra',
       'SonataSport', 'SonataLimited', 'Sonata1.6T', 'Elantra4DSD',
       'Elantra4DR', 'ElantraSEL', 'ElantraSport', 'ElantraECO',
       'SonataEco', 'AccentSE', 'Accent4dr', 'Sonata2.0T', 'Tiburon2dr',
       'Elantra5dr', 'AccentValue', 'AccentGS', 'AccentGLS', 'Genesis',
       'AccentSport', 'VelosterManual', 'Accent3dr', 'TucsonSE',
       'TucsonFWD', 'TucsonGLS', 'SonataSEL', 'Accent5dr',
       'VelosterAutomatic', 'VelosterRE:MIX', 'VelosterDual', 'TucsonAWD',
       'Azera4dr', 'TucsonGL', 'AzeraSedan', 'VelosterTurbo',
       'VelosterValue', 'Veloster3dr', 'Tucson4WD', 'TucsonLimited',
       'Santa', 'VelosterRE:FLEX', 'Tucson4dr', 'TucsonEco',
       'TucsonSport', 'AzeraLimited', 'SonataBase', 'Accent',
       'Genesis4dr', 'TucsonNight', 'Ioniq', 'XG3004dr', 'Genesis3.8',
       'VeracruzAWD', 'TucsonWalking', 'VeracruzFWD', 'Veloster1.6L',
       'XG3504dr', 'Genesis5.0', 'Entourage4dr', 'Genesis3.8L',
       'GenesisV6', 'Azera3.3L', 'Equus4dr', 'EquusSignature',
       'Genesis5.0L', 'EquusUltimate', 'M45Sport', 'M45Base', 'G25',
       'M454dr', 'QX4Luxury', 'QX4QX4', 'M354dr', 'G37', 'G35',
       'G20Luxury', 'G20Touring', 'Q50AWD', 'Q40RWD', 'Q40AWD',
       'I35Luxury', 'Q50RWD', 'M35x', 'M35Sport', 'Q50Hybrid', 'EX35RWD',
       'M35Base', 'EX35AWD', 'Q504dr', 'QX50AWD', 'Q503.0t', 'Q502.0t',
       'EX37EX37', 'QX50RWD', 'QX30Base', 'FX35AWD', 'FX35Base',
       'QX30Sport', 'Q70V6', 'QX602WD', 'FX354dr', 'QX60FWD', 'Q50',
       'M35hM35h', 'QX30Luxury', 'FX45AWD', 'QX60AWD', 'FX35RWD',
       'I30Luxury', 'QX30FWD', 'I30Touring', 'FX37FX37', 'QX30Premium',
       'M374dr', 'Q60', 'QX30AWD', 'Q70LV6', 'M564dr', 'FX35with',
       'QX60Hybrid', 'EX37Journey', 'Q45Base', 'M56x', 'FX50AWD',
       'QX70AWD', 'QX70RWD', 'I30Limited', 'M37Base', 'M37x', 'M37M37',
       'FX35Limited', 'QX70V6', 'QX564dr', 'Q603.0t', 'QX562WD',
       'JX35JX35', 'M37M37x', 'QX60Base', 'QX564WD', 'Q602.0t', 'M56M56',
       'I30Automatic', 'QX56RWD', 'Q703.7', 'M37X', 'Q45Premium',
       'M56M56x', 'QX56AWD', 'Q50Red', 'FX50FX50', 'Q70LV8', 'Q45with',
       'Q70V8', 'FX352', 'Q70hHybrid', 'Q70L3.7', 'QX60', 'QX56Base',
       'QX70V8', 'QX802WD', 'QX804WD', 'Q70L5.6', 'Q705.6', 'QX80RWD',
       'QX80AWD', 'i-2902WD', 'Axiom4dr', 'i-2802dr', 'Rodeo4dr',
       'Trooper4dr', 'VehiCROSS2dr', 'Ascender4dr', 'Ascender2WD',
       'HombreSpacecab', 'HombreReg', 'i-3504dr', 'XK82dr', 'S-TYPE4dr',
       'XFPremium', 'X-TYPE4dr', 'XF4dr', 'XFI4', 'XFXF', 'XF2009',
       'XFSport', 'XFPortfolio', 'XFV6', 'XF35t', 'XK2dr', 'XJ4dr',
       'XE25t', 'XK', 'XJ', 'XE20d', 'XF', 'XFV8', 'XE35t', 'XFXFR',
       'XF20d', 'XJL', 'XKXK', 'XJRWD', 'XKXKR', 'XJAWD', 'XFR', 'XFS',
       'XFSupercharged', 'F-PACE35t', 'XJBase', 'F-PACE25t', 'F-PACE20d',
       'XJSupercharged', 'XKCoupe', 'XKR', 'XJR', 'XFXFR-S', 'XFR-Sport',
       'F-TYPEF-Type', 'XKConvertible', 'F-TYPECoupe',
       'F-TYPEConvertible', 'F-PACES', 'XJR-Sport', 'XJXJL', 'XKXKR-S',
       'XFR-S', 'F-PACEFirst', 'XKR-S', 'F-TYPESVR', 'CompassSport',
       'CompassLatitude', 'CompassHigh', 'Cherokee4WD', 'CompassFWD',
       'Compass4WD', 'CherokeeLatitude', 'CherokeeSport',
       'CompassAltitude', 'CherokeeFWD', 'Compass75th', 'CompassLatutide',
       'RenegadeSport', 'PatriotSport', 'CompassLimited',
       'CherokeeAltitude', 'CherokeeLimited', 'PatriotLatitude',
       'CherokeeHigh', 'Compass2WD', 'PatriotFWD', 'Compass2017.5',
       'Compass', 'RenegadeLatitude', 'Patriot75th', 'PatriotAltitude',
       'PatriotHigh', 'PatriotLimited', 'Patriot4WD', 'RenegadeLimited',
       'Cherokee75th', 'LibertyRWD', 'CherokeeTrailhawk', 'PatriotSPORT',
       'Renegade75th', 'PatriotNorth', 'Liberty4dr', 'Liberty4WD',
       'RenegadeJustice', 'CommanderRWD', 'Renegade4WD', 'Patriot2WD',
       'RenegadeTrailhawk', 'CherokeeOverland', 'Cherokee4dr',
       'Commander4WD', 'Commander4dr', 'CompassTrailhawk', 'Liberty2WD',

In [16]:
cars.Model = cars.Model.apply(lambda X:X.replace("-",""))

In [17]:
cars.Model = cars.Model.apply(lambda X:X.replace("+",""))

In [18]:
cars.Model = cars.Model.apply(lambda X:X.replace(".",""))

In [19]:
cars.Model = cars.Model.apply(lambda X:X.replace("*",""))

In [23]:
cars=cars.sample(10000)

       index  Price  Year  Mileage       Make           Model
0     273094  19397  2016    40450       Ford       EscapeFWD
1     754808  16998  2015     7066     Toyota        CorollaS
2     175496  38970  2015    59651  Chevrolet     Suburban2WD
3      20279  33999  2015    30215       Audi           Q730T
4     398089  13999  2010    66214      Honda          Accord
...      ...    ...   ...      ...        ...             ...
9995   87517  17233  2017    28178  Chevrolet        MalibuLT
9996  232057  27995  2014    46090      Dodge  DurangoLimited
9997  808528   9500  2013   110239     Toyota   TacomaRegular
9998  346969  37995  2014    56179       Ford         F1504WD
9999  331456  31245  2016    29446       Ford     Explorer4WD

[10000 rows x 6 columns]

In [29]:
cars.drop(columns=['index'])

      Price  Year  Mileage       Make           Model
0     19397  2016    40450       Ford       EscapeFWD
1     16998  2015     7066     Toyota        CorollaS
2     38970  2015    59651  Chevrolet     Suburban2WD
3     33999  2015    30215       Audi           Q730T
4     13999  2010    66214      Honda          Accord
...     ...   ...      ...        ...             ...
9995  17233  2017    28178  Chevrolet        MalibuLT
9996  27995  2014    46090      Dodge  DurangoLimited
9997   9500  2013   110239     Toyota   TacomaRegular
9998  37995  2014    56179       Ford         F1504WD
9999  31245  2016    29446       Ford     Explorer4WD

[10000 rows x 5 columns]

In [30]:
cars

       index  Price  Year  Mileage       Make           Model
0     273094  19397  2016    40450       Ford       EscapeFWD
1     754808  16998  2015     7066     Toyota        CorollaS
2     175496  38970  2015    59651  Chevrolet     Suburban2WD
3      20279  33999  2015    30215       Audi           Q730T
4     398089  13999  2010    66214      Honda          Accord
...      ...    ...   ...      ...        ...             ...
9995   87517  17233  2017    28178  Chevrolet        MalibuLT
9996  232057  27995  2014    46090      Dodge  DurangoLimited
9997  808528   9500  2013   110239     Toyota   TacomaRegular
9998  346969  37995  2014    56179       Ford         F1504WD
9999  331456  31245  2016    29446       Ford     Explorer4WD

[10000 rows x 6 columns]

In [57]:
cars.describe()

              Price         Year        Mileage
count   9735.000000  9735.000000    9735.000000
mean   20089.215100  2013.235131   53240.725218
std     9542.772384     3.402201   40980.702779
min     1689.000000  1997.000000       5.000000
25%    12995.000000  2012.000000   24604.500000
50%    17998.000000  2014.000000   41008.000000
75%    25995.000000  2016.000000   72859.000000
max    49998.000000  2018.000000  400483.000000

In [58]:
cars = cars[cars.Price<50000]

In [59]:
cars

      Price  Year  Mileage       Make           Model
0     19397  2016    40450       Ford       EscapeFWD
1     16998  2015     7066     Toyota        CorollaS
2     38970  2015    59651  Chevrolet     Suburban2WD
3     33999  2015    30215       Audi           Q730T
4     13999  2010    66214      Honda          Accord
...     ...   ...      ...        ...             ...
9995  17233  2017    28178  Chevrolet        MalibuLT
9996  27995  2014    46090      Dodge  DurangoLimited
9997   9500  2013   110239     Toyota   TacomaRegular
9998  37995  2014    56179       Ford         F1504WD
9999  31245  2016    29446       Ford     Explorer4WD

[9735 rows x 5 columns]

In [60]:
cars.reset_index(drop=True)

      Price  Year  Mileage       Make           Model
0     19397  2016    40450       Ford       EscapeFWD
1     16998  2015     7066     Toyota        CorollaS
2     38970  2015    59651  Chevrolet     Suburban2WD
3     33999  2015    30215       Audi           Q730T
4     13999  2010    66214      Honda          Accord
...     ...   ...      ...        ...             ...
9730  17233  2017    28178  Chevrolet        MalibuLT
9731  27995  2014    46090      Dodge  DurangoLimited
9732   9500  2013   110239     Toyota   TacomaRegular
9733  37995  2014    56179       Ford         F1504WD
9734  31245  2016    29446       Ford     Explorer4WD

[9735 rows x 5 columns]

In [61]:
cars.drop(columns=['index'],inplace=True)

KeyError: "['index'] not found in axis"

In [53]:
cars

      Price  Year  Mileage       Make           Model
0     19397  2016    40450       Ford       EscapeFWD
1     16998  2015     7066     Toyota        CorollaS
2     38970  2015    59651  Chevrolet     Suburban2WD
3     33999  2015    30215       Audi           Q730T
4     13999  2010    66214      Honda          Accord
...     ...   ...      ...        ...             ...
9995  17233  2017    28178  Chevrolet        MalibuLT
9996  27995  2014    46090      Dodge  DurangoLimited
9997   9500  2013   110239     Toyota   TacomaRegular
9998  37995  2014    56179       Ford         F1504WD
9999  31245  2016    29446       Ford     Explorer4WD

[9735 rows x 5 columns]

In [55]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9735 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Price    9735 non-null   int64
 1   Year     9735 non-null   int64
 2   Mileage  9735 non-null   int64
 3   Make     9735 non-null   object
 4   Model    9735 non-null   object
dtypes: int64(3), object(2)
memory usage: 456.3+ KB

## Model

In [62]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [63]:
inp = cars[['Year','Mileage','Make','Model']]
op = cars[['Price']]

In [64]:
inp

      Year  Mileage       Make           Model
0     2016    40450       Ford       EscapeFWD
1     2015     7066     Toyota        CorollaS
2     2015    59651  Chevrolet     Suburban2WD
3     2015    30215       Audi           Q730T
4     2010    66214      Honda          Accord
...    ...      ...        ...             ...
9995  2017    28178  Chevrolet        MalibuLT
9996  2014    46090      Dodge  DurangoLimited
9997  2013   110239     Toyota   TacomaRegular
9998  2014    56179       Ford         F1504WD
9999  2016    29446       Ford     Explorer4WD

[9735 rows x 4 columns]

In [65]:
op

      Price
0     19397
1     16998
2     38970
3     33999
4     13999
...     ...
9995  17233
9996  27995
9997   9500
9998  37995
9999  31245

[9735 rows x 1 columns]

In [66]:
ohe = OneHotEncoder()
ohe.fit(inp[["Year","Make","Model"]])

OneHotEncoder()

In [ ]:
pipe = make_pipeline()